stages:
  transform:
    cmd: python backend/src/data_transform.py
    deps:
      - backend/data/raw/email_dataset.csv
      - backend/src/data_transform.py
    outs:
      - backend/data/processed/email_dataset_processed.csv
    params:
      - data.raw_path
      - data.processed_path

  train:
    cmd: python backend/src/training.py
    deps:
      - backend/data/processed/email_dataset_processed.csv
      - backend/src/training.py
      - backend/src/data_transform.py
      - params.yaml
    outs:
      - mlflow_artifacts/training_info.json
    params:
      - data.processed_path
      - preprocessing
      - model_variants
      - mlflow

  evaluate:
    cmd: python backend/src/evaluation.py
    deps:
      - backend/data/processed/email_dataset_processed.csv
      - backend/src/evaluation.py
      - backend/src/data_transform.py
      - params.yaml
      - mlflow_artifacts/training_info.json
    outs:
      - mlflow_artifacts/evaluation_report.csv
      - backend/models
    params:
      - data.processed_path
      - preprocessing
      - mlflow

